spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GameJourneys
    name: GameJourneys
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
jwt:
  secret: Ejk8yT%[dae,G+vMVEpCPpc5:Nj!%kXG{=bH/V]Vf_;U{?RA[S4!KN8c??_v!E(dCVUr
