INSERT INTO games (dtype, game_name) VALUES ('Game', 'Demon\'s Souls');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Dark Souls');
INSERT INTO games (dtype, game_name, remastered_game_id) VALUES ('Remaster', 'Dark Souls Remastered', 2);
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Dark Souls II');
INSERT INTO games (dtype, game_name, remastered_game_id) VALUES ('Remaster', 'Dark Souls II: Scholar of the First Sin', 4);
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Dark Souls III');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Bloodborne');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Sekiro: Shadows Die Twice');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Elden Ring');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Armored Core');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Metal Wolf Chaos');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'King\'s Field');
INSERT INTO games (dtype, game_name, remastered_game_id) VALUES ('Remaster', 'Metal Wolf Chaos XD', 11);
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Echo Night');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Enchanted Arms');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Evergrace');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Shadow Tower Abyss');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Kuon');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Lost Kingdoms II');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Steel Battalion');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Murakumo: Renegade Mech Pursuit');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Deraciné');

INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: The Adventure of Link');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: A Link to the Past');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Link\'s Awakening');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Ocarina of Time');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Majora\'s Mask');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Oracle of Ages');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Oracle of Seasons');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Four Swords');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: The Wind Waker');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: The Minish Cap');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Twilight Princess');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Phantom Hourglass');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Spirit Tracks');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Skyward Sword');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: A Link Between Worlds');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Tri Force Heroes');
INSERT INTO games (dtype, game_name) VALUES ('Game', 'The Legend of Zelda: Breath of the Wild');

INSERT INTO games (dtype, game_name, remade_game_id) VALUES ('Remake', 'Demon\'s Souls', 1);
INSERT INTO games (dtype, game_name) VALUES ('Game', 'Final Fantasy VII');
INSERT INTO games (dtype, game_name, remade_game_id) VALUES ('Remake', 'Final Fantasy VII Remake', 42);
