INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls'), (SELECT id FROM series WHERE series_name = 'Dark Souls'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls Remastered'), (SELECT id FROM series WHERE series_name = 'Dark Souls'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls II'), (SELECT id FROM series WHERE series_name = 'Dark Souls'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls II: Scholar of the First Sin'), (SELECT id FROM series WHERE series_name = 'Dark Souls'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls III'), (SELECT id FROM series WHERE series_name = 'Dark Souls'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: The Adventure of Link'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: A Link to the Past'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Link\'s Awakening'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Ocarina of Time'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Majora\'s Mask'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Oracle of Ages'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Oracle of Seasons'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Four Swords'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: The Wind Waker'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: The Minish Cap'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Twilight Princess'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Phantom Hourglass'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Spirit Tracks'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Skyward Sword'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: A Link Between Worlds'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Tri Force Heroes'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Breath of the Wild'), (SELECT id FROM series WHERE series_name = 'The Legend of Zelda'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'Final Fantasy VII'), (SELECT id FROM series WHERE series_name = 'Final Fantasy'));
INSERT INTO games_series (game_id, series_id) VALUES ((SELECT id FROM games WHERE game_name = 'Final Fantasy VII Remake'), (SELECT id FROM series WHERE series_name = 'Final Fantasy'));
