INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls Remastered'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls II'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls II: Scholar of the First Sin'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Dark Souls III'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Demon\'s Souls' ORDER BY id DESC LIMIT 1), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Demon\'s Souls' LIMIT 1), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Bloodborne'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Final Fantasy VII Remake'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Final Fantasy VII'), ((SELECT id FROM genres WHERE genre_name = 'Role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: The Adventure of Link'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: The Adventure of Link'), ((SELECT id FROM genres WHERE genre_name = 'Platformer')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: A Link to the Past'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Link\'s Awakening'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Ocarina of Time'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Majora\'s Mask'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Oracle of Ages'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Oracle of Seasons'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Four Swords'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: The Wind Waker'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: The Minish Cap'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Twilight Princess'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Phantom Hourglass'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Spirit Tracks'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Skyward Sword'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: A Link Between Worlds'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Tri Force Heroes'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'The Legend of Zelda: Breath of the Wild'), ((SELECT id FROM genres WHERE genre_name = 'Action-adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Déraciné'), ((SELECT id FROM genres WHERE genre_name = 'Adventure')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Elden Ring'), ((SELECT id FROM genres WHERE genre_name = 'Action role-playing')));
INSERT INTO games_genres (game_id, genre_id) VALUES ((SELECT id FROM games WHERE game_name = 'Armored Core'), ((SELECT id FROM genres WHERE genre_name = 'Third-person shooter')));
