INSERT INTO publishers (publisher_name) VALUES ('Electronic Arts');
INSERT INTO publishers (publisher_name) VALUES ('Ubisoft');
INSERT INTO publishers (publisher_name) VALUES ('Activision Blizzard');
INSERT INTO publishers (publisher_name) VALUES ('Nintendo');
INSERT INTO publishers (publisher_name) VALUES ('Sony Interactive Entertainment');
INSERT INTO publishers (publisher_name) VALUES ('Microsoft Studios');
INSERT INTO publishers (publisher_name) VALUES ('Square Enix');
INSERT INTO publishers (publisher_name) VALUES ('Take-Two Interactive');
INSERT INTO publishers (publisher_name) VALUES ('Bethesda Softworks');
INSERT INTO publishers (publisher_name) VALUES ('Capcom');
INSERT INTO publishers (publisher_name) VALUES ('Bandai Namco Entertainment');
INSERT INTO publishers (publisher_name) VALUES ('Sega');
INSERT INTO publishers (publisher_name) VALUES ('Konami');
INSERT INTO publishers (publisher_name) VALUES ('EA Sports');
INSERT INTO publishers (publisher_name) VALUES ('2K Games');
INSERT INTO publishers (publisher_name) VALUES ('FromSoftware');
INSERT INTO publishers (publisher_name) VALUES ('Namco Bandai Games');
